//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomPlanner.WinFormsStrings", typeof(WinFormsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add furniture.
        /// </summary>
        internal static string addFurnitureBox_Text {
            get {
                return ResourceManager.GetString("addFurnitureBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen table.
        /// </summary>
        internal static string button1_AccessibleName {
            get {
                return ResourceManager.GetString("button1.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string button2_AccessibleName {
            get {
                return ResourceManager.GetString("button2.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofa.
        /// </summary>
        internal static string button3_AccessibleName {
            get {
                return ResourceManager.GetString("button3.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string button4_AccessibleName {
            get {
                return ResourceManager.GetString("button4.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string button5_AccessibleName {
            get {
                return ResourceManager.GetString("button5.AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created furniture.
        /// </summary>
        internal static string createdFurnitureBox_Text {
            get {
                return ResourceManager.GetString("createdFurnitureBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Planner.
        /// </summary>
        internal static string Form1_Text {
            get {
                return ResourceManager.GetString("Form1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bluperint.
        /// </summary>
        internal static string newBlueprintToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("newBlueprintToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string openToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("openToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string polishToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("polishToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saveToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
